#!/usr/bin/env bash
#MISE description="Deploy all k8s resources for local environment (platform + workloads)"
#MISE depends=["k8s:local:deploy-platform"]

echo "Deploying workload resources for local environment..."
kubectl apply -k k8s/overlays/local/workloads
