#!/usr/bin/env bash
#MISE description="Create kind cluster for local development"

cat <<EOF | kind create cluster --name foresee --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
EOF
