#!/usr/bin/env bash
#MISE description="Run Go lint"
#MISE arg "service" help="Service name (e.g., transaction). If not specified, runs lint on all services"

if [ -n "$1" ]; then
  cd "services/$1" || exit 1
  go vet ./...
else
  go vet ./services/...
fi
